## URL ##
# URL instance is to be accessible by.
# Do not reuse domains after starting an instance.
# Do not change after you start the instance for the first time.
##
url: "https://example.com/"

host: "0.0.0.0"
port: 9782


### Appearance ###
# Determine how this instance appears to other instances and to your users

## Name ##
# Display name for this instance
##
name: "Aster"

## Description ##
# Optional description for this instance
##
description: ""

## Theme Color ##
# Color to represent this instance
##
color: "#140e1b"

## Maintainer Information ##
# Provide your name and email for other instances to contact you
##
maintainer:
    name: you
    email: you@example.com


## Registrations ##
# options:
#   open      - anyone can register
#   approval  - anyone can register but cannot use their account until approved
#   invite    - only people with invite codes can register
#   closed    - nobody can register
##
registrations: invite

## Identifiers ##
# ID format to use. Keep as default unless migrating from elsewhere.
# options: aidx, aid, uuid
##
identifiers: aidx

## Database ##
database:
    host: localhost
    port: 5432
    db: aster
    user: aster
    password: aster

## Queue ##
# Queues are how Aster handles federating
#   concurrency: how many jobs can be run at a time
#   maxRetries: how many times a job can be retries before discarded
##
queue:
    inbox:
        concurrency: 5
        maxRetries: 10
    deliver:
        concurrency: 20
        maxRetries: 15
    backfill:
        concurrency: 4
        maxRetries: 10

## Timeline ##
# Default objects:
#   Too high of a number will slow down timeline requests.
# Max objects:
#   Too high of a number will allow higher amounts if needed,
#   but not cause as much strain as a high default.
# Authentication:
#   You may want to make your timelines require auth if
#   your infrastructure can't handle extra pressure from
#   people outside your instance or scrapers.
##
timeline:
    defaultObjects: 15
    maxObjects: 35

    local:
        authRequired: false
    bubble:
        authRequired: false
        hosts: [ ]
    public:
        authRequired: false

## Note Settings ##
# Max lengths cannot be higher than 100000
# Max attachments are the maximum amount of files per note
##
note:
    maxLength:
        cw: 1024
        content: 8192
    maxAttachments: 10

## File storage ##
# How to store files uploaded by users.
#   type:
#     local   - Store in local filesystem
#   localPath: Path to store files at
#   maxUploadSize: In MB, maximum file size
##
fileStorage:
    type: local
    localPath: '/var/lib/aster/files'
    maxUploadSize: 25

## Hide remote content ##
# This prevents potentially bad things to be hosted to the
# public on your instance. Only authenticated uses will be
# able to see remote content. Recommended to keep on, unless
# you're a very active moderator.
##
hideRemoteContent: true

## Max resolve depth ##
# Maximum number of recursive resolves before stopping.
# Prevents infinitely fetching notes.
##
maxResolveDepth: 25

## Reserved usernames ##
# Nobody can register an account with these usernames.
# Case-insensitive.
##
reservedUsernames:
    - admin
    - administrator
    - system
    - webmaster
    - noreply
    - instanceactor
    - proxy
    - systemproxy
    - instanceproxy
    - aster
    - mastodon
    - misskey

## Use default frontend ##
# Whether to use the frontend packaged with the server
# or to leave it up for plugins to handle.
# Disabling without a plugin to add an alternate frontend
# will make your instance unusable to most users.
##
builtinFrontend: true

## Debug ##
# Only enable if you need detailed information for development.
# Otherwise, this will needlessly slow down runtime.
##
debug: true
